import './globals.css'
import type { Metadata } from 'next'
import { Saira } from 'next/font/google'
import RootStyleRegistry from './RootStyleRegistry'

const saira = Saira({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin']
})

import Header from '@/components/header/Header'
import { FilterContextProvider } from '@/contexts/Filter-Context'

export const metadata: Metadata = {
  title: 'Capputeeno',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <FilterContextProvider>
          <RootStyleRegistry>
            <Header />
            {children}
          </RootStyleRegistry>
        </FilterContextProvider>
      </body>
    </html>
  )
}
